### ISSUE TITLE
test fails

### ISSUE THREAD

**Issue by lega911** [playing-se/swish-python#4]
Hello!

I have this problem on Digital Ocean (Amsterdam) and on localhost, is it problem of swish server?
```
# cat /etc/issue
Ubuntu 14.04.1 LTS \n \l

swish-python/tests# python -m unittest test_client

./usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connection.py:303: SubjectAltNameWarning: Certificate for mss.swicpc.bankgirot.se has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
...

E
======================================================================
ERROR: test_create_payment_ecommerce (test_client.SwishClientTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_client.py", line 35, in test_create_payment_ecommerce
    message='Kingston USB Flash Drive 8 GB'
  File "/usr/local/lib/python2.7/dist-packages/swish-1.0b1-py2.7.egg/swish/client.py", line 45, in create_payment
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: https://mss.swicpc.bankgirot.se/swish-cpcapi/api/v1/paymentrequests

======================================================================
ERROR: test_create_payment_error (test_client.SwishClientTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_client.py", line 59, in test_create_payment_error
    message='BE18'
  File "/usr/local/lib/python2.7/dist-packages/swish-1.0b1-py2.7.egg/swish/client.py", line 45, in create_payment
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: https://mss.swicpc.bankgirot.se/swish-cpcapi/api/v1/paymentrequests

======================================================================
ERROR: test_create_payment_mcommerce (test_client.SwishClientTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_client.py", line 46, in test_create_payment_mcommerce
    message='Kingston USB Flash Drive 8 GB'
  File "/usr/local/lib/python2.7/dist-packages/swish-1.0b1-py2.7.egg/swish/client.py", line 45, in create_payment
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: https://mss.swicpc.bankgirot.se/swish-cpcapi/api/v1/paymentrequests

======================================================================
ERROR: test_create_refund (test_client.SwishClientTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_client.py", line 83, in test_create_refund
    message='Kingston USB Flash Drive 8 GB'
  File "/usr/local/lib/python2.7/dist-packages/swish-1.0b1-py2.7.egg/swish/client.py", line 45, in create_payment
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: https://mss.swicpc.bankgirot.se/swish-cpcapi/api/v1/paymentrequests

======================================================================
ERROR: test_get_payment (test_client.SwishClientTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_client.py", line 68, in test_get_payment
    message='Kingston USB Flash Drive 8 GB'
  File "/usr/local/lib/python2.7/dist-packages/swish-1.0b1-py2.7.egg/swish/client.py", line 45, in create_payment
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: https://mss.swicpc.bankgirot.se/swish-cpcapi/api/v1/paymentrequests

======================================================================
ERROR: test_get_refund (test_client.SwishClientTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_client.py", line 104, in test_get_refund
    message='Kingston USB Flash Drive 8 GB'
  File "/usr/local/lib/python2.7/dist-packages/swish-1.0b1-py2.7.egg/swish/client.py", line 45, in create_payment
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: https://mss.swicpc.bankgirot.se/swish-cpcapi/api/v1/paymentrequests

----------------------------------------------------------------------
Ran 7 tests in 7.713s

FAILED (errors=6)
```

**Comment by MadSpindel** [comment]
Looks like the Swish Test Environment is down. It have been down before. We should probably mock the url with Responses (https://github.com/getsentry/responses) so the tests runs even when the test environment is down.

**Comment by MadSpindel** [comment]
Seems to work again. @lega911 could you please try again now?

**Comment by lega911** [comment]
Yes, it works. Thank you.
